/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "STM32F103x8.h"
#include "stm32f103x8_gpio_driver.h"
#include "lcd.h"
#include "keypad.h"
#include "stm32f103x8_EXTI_driver.h"
#include "stm32f103x8_USART_driver.h"
#include "stm32f103x8_SPI_driver.h"
#include "stm32f103x8_I2C_driver.h"
#include "I2C_Slave_EEPROM.h"

int val1 = 0;

uint8_t IRQ_Flag = 0;


enum CPU_ACCESS_LEVEL{
	PRIVILEGED,
	UNPRIVILEGED
};

void SWITCH_ACCESS_LEVEL(enum CPU_ACCESS_LEVEL level){
	switch (level){
	case PRIVILEGED:
		/* Clear Bit 0 in CONTROL Register */
		__asm("mrs r3, CONTROL \n\t"
				"lsr r3,r3, #0x1 \n\t"
				"lsl r3,r3 ,0x1 \n\t"
				"msr CONTROL, r3");
		break;
	case UNPRIVILEGED:
		/* Set Bit 0 in CONTROL Register */
		__asm("mrs r3, CONTROL \n\t"
				"orr r3,r3,#0x1 \n\t"
				"msr CONTROL,r3");

		break;
	}
}


void EXTI9_CALLBACK(void)
{
	IRQ_Flag = 1;

	SWITCH_ACCESS_LEVEL(PRIVILEGED);

}


void NMI_Handler(){


}
void HardFault_Handler(){


}
void MemManage_Handler(){


}

void BusFault_Handler(){


}

void UsageFault_Handler(){

}

void SVC_Handler(){

}
void DebugMon_Handler(){


}
void PendSV_Handler(){

}



int main(void)
{
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	//Set EXTI Configuration
	EXTI_PinConfig_t EXTIConfig;
	EXTIConfig.EXTI_PIN = EXTI9PB9;
	EXTIConfig.Trigger_Case = EXTI_Trigger_RISING;
	EXTIConfig.P_IRQ_CallBack = EXTI9_CALLBACK;
	EXTIConfig.IRQ_EN = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTIConfig);


	IRQ_Flag = 1;
//	__asm("nop \n\t nop \n\t nop \n\t");
//
//	//__asm("mov %0, #0xff"
//	//	:"=r" (val1));
//
//	__asm("mov r0, %0"
//	:
//	:"r" (val1));
//
//
__asm("nop \n\t nop \n\t nop \n\t");
SWITCH_ACCESS_LEVEL(UNPRIVILEGED);


__asm("nop \n\t nop \n\t nop \n\t");

	while (1)
	{
		if(IRQ_Flag)
		{
			IRQ_Flag = 0;
		}
		else { /* Misra */ }
	}


}
